name: Docker Image CI

env:
  DOCKER_IMAGE_NAME: rprj-ng

permissions:
  contents: write       # I must update the version number
  packages: write       # required to push to GHCR with GITHUB_TOKEN

on:
  push:
    branches: [ "main" ]
    paths:
      - "be/**"
      - "fe/**"
      - ".github/workflows/docker-image.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "be/**"
      - "fe/**"
      - ".github/workflows/docker-image.yml"

jobs:
  test:
    name: BE Quality Checks
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'be/') || contains(github.event.head_commit.added, 'be/')

    services:
      postgres:
        image: postgres:18.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecret
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mysecret
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Run Tests for PostgreSQL, MariaDB, and SQLite
        env:
          DB_TYPE: postgres,mysql,sqlite
        run: |
          cd be
          go test ./dblayer --config ../config_test_postgresql.json
          go test ./dblayer --config ../config_test_mysql.json
          go test ./dblayer --config ../config_test_sqlite.json

  build:
    # Apparently this "needs: test" blocks the build job if the test job is skipped (no changes in "be/")
    #needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Read VERSION file
      id: ver
      run: |
        if [ ! -f VERSION ]; then
          echo "VERSION file not found" >&2
          exit 1
        fi
        # trim newline/carriage returns
        version=$(tr -d '\r\n' < VERSION)
        echo "tag=$version" >> "$GITHUB_OUTPUT"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push BE image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./be
        file: ./be/Dockerfile        # optional if Dockerfile is named Dockerfile in ./be
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-be:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-be:${{ steps.ver.outputs.tag }}

    - name: Build and push FE image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./fe
        file: ./fe/Dockerfile        # optional if Dockerfile is named Dockerfile in ./be
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-fe:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}-fe:${{ steps.ver.outputs.tag }}

    - name: Increase version number for the next release
      run: |
        version=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$version"
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        echo "$new_version" > VERSION
        echo "Next version: $new_version"

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to $new_version" || echo "No changes to commit"
        git push

