name: Go Server Dev Build

on:
  push:
    branches:
      - main
    paths:
      - "be/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecret
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # mysql:
      #   image: mariadb:12.0
      #   env:
      #     MYSQL_ROOT_PASSWORD: mysecret
      #     MYSQL_DATABASE: testdb
      #   ports:
      #     - 3306:3306
      #   options: >-
      #     --health-cmd="mysqladmin ping -h localhost"
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=5

    strategy:
      #max-parallel: 1
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Run Tests for PostgreSQL, MySQL, and SQLite
        env:
          DB_TYPE: postgres,mysql,sqlite
        run: |
          cd be
          go test ./dblayer --config ../config_test_postgresql.json
        # go test ./dblayer --config ../config_test_mysql.json
        # go test ./dblayer --config ../config_test_sqlite.json

      - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          cd be
          OUTDIR="../build/${{ matrix.goos }}/${{ matrix.goarch }}"
          mkdir -p "$OUTDIR"
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          FILENAME="rhobee-be-${{ matrix.goos }}-${{ matrix.goarch }}$EXT"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$OUTDIR/$FILENAME" .

      - name: Upload to dev release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev
          name: "Development Build"
          prerelease: true
          overwrite_files: true
          files: build/${{ matrix.goos }}/${{ matrix.goarch }}/rhobee-be-*
